version: "3.8"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      MODEL_IMPL: bert  # or fasttext
      MODEL_PATH: /app/models/bert  # or /app/models/fasttext
    volumes:
      - ./:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
